# Data Science Tools and Ecosystem

In this notebook, Data Science Tools and Ecosystem are summarized.

Some of the popular languages that Data Scientists use are:
1. python
2. R
3. java

Some of the commonly used libraries used by Data Scientists include:
1. numpy
2. pandas
3. scikit-learn
4. seaborn

| Data Science Tools|
| --- | 
| Jupiter Notebook | 
| RStudio |
| Jupiter Lab | 


### Below are a few examples of evaluating arithmetic expressions in Python

In [1]:
# This a simple arithmetic expression to mutiply then add integers
(3*4)+5

17

In [2]:
# This will convert 200 minutes to hours by diving by 60

200/60

3.3333333333333335

*Objectives:*
- calculations
- markdown
- data science libraries 

## Author
Tadeusz Mięsowicz

In [4]:
import numpy as np
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [6]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [7]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

In [9]:
var = '01234567'
var[::2]

'0246'

In [11]:

1/2

0.5

In [12]:
a=np.array([0,1,0,1,0]) 
b=np.array([1,0,1,0,1]) 
a*b

array([0, 0, 0, 0, 0])

In [15]:
a=np.array([10,9,8,7,6])
a+1

array([11, 10,  9,  8,  7])